"""add parties table

Revision ID: 5e0bd2946a2a
Revises: 1b1793ecfdd7
Create Date: 2022-05-04 16:42:16.513237

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5e0bd2946a2a"
down_revision = "1b1793ecfdd7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parties",
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("campaign_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "player_character_party",
        sa.Column("player_character_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("party_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["parties.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["player_character_id"],
            ["player_characters.uuid"],
        ),
        sa.PrimaryKeyConstraint("player_character_id", "party_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_character_party")
    op.drop_table("parties")
    # ### end Alembic commands ###
