"""Add player character relationship table

Revision ID: 63dbe9e03b43
Revises: 1b1793ecfdd7
Create Date: 2022-05-02 19:06:58.832394

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "63dbe9e03b43"
down_revision = "1b1793ecfdd7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_character_relationships",
        sa.Column("player_character_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("character_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "character_entity",
            postgresql.ENUM(
                "PlayerCharacter", "NPC", name="character_enum", create_type=True
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "FRIENDLY",
                "NEUTRAL",
                "HOSTILE",
                name="relationship_status_enum",
                create_type=True,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_character_id"],
            ["player_characters.uuid"],
        ),
        sa.PrimaryKeyConstraint("player_character_id", "character_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_character_relationships")
    character_enum = postgresql.ENUM("PlayerCharacter", "NPC", name="character_enum")
    character_enum.drop(op.get_bind())

    relationship_status_enum = postgresql.ENUM(
        "FRIENDLY", "NEUTRAL", "HOSTILE", name="relationship_status_enum"
    )
    relationship_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
