"""Add user id field to campaign table

Revision ID: 7c347be1029f
Revises: 509455681492
Create Date: 2022-04-29 22:33:49.838952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c347be1029f'
down_revision = '509455681492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'campaigns',
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False)
    )
    op.alter_column(
        'campaigns', 'name',
        existing_type=sa.VARCHAR(),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'user_id')
    op.alter_column(
        'campaigns', 'name',
        existing_type=sa.VARCHAR(),
        nullable=True
    )
    # ### end Alembic commands ###
